alias: TESTING
description: ""
trigger:
  - platform: state
    entity_id:
      - input_boolean.test_alarm_control_1
    to: "on"
    id: "Czujka pierwsza wykryła ruch"
  - platform: state
    entity_id:
      - input_boolean.test_alarm_control_2
    to: "on"
    id: "Czujka druga wykryła ruch"
  - platform: state
    entity_id:
      - input_boolean.test_alarm_control_3
    to: "on"
    id: "Czujka trzecia wykryła ruch"
  - platform: state
    entity_id:
      - input_boolean.test_alarm_control_1
    to: "off"
    id: "Czujka pierwsza przestała wykrywać ruch"
  - platform: state
    entity_id:
      - input_boolean.test_alarm_control_2
    to: "off"
    id: "Czujka druga przestała wykrywać ruch"
  - platform: state
    entity_id:
      - input_boolean.test_alarm_control_3
    to: "off"
    id: "Czujka trzecia przestała wykrywać ruch"
condition: []
action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id:
                  - "Czujka pierwsza wykryła ruch"
                  - "Czujka druga wykryła ruch"
                  - "Czujka trzecia wykryła ruch"
        sequence:
          - service: input_text.set_value
            target:
              entity_id: input_text.test_alarm_control_output
            data:
              value: "{{ trigger.id }}"
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id:
                  - "Czujka pierwsza przestała wykrywać ruch"
                  - "Czujka druga przestała wykrywać ruch"
                  - "Czujka trzecia przestała wykrywać ruch"
        sequence:
          - service: input_text.set_value
            target:
              entity_id: input_text.test_alarm_control_output
            data:
              value: "{{ trigger.id }}"
mode: single
